// Redux Toolkit slice for patient management.
// Replaces the previous separate actions/reducer approach with a concise slice.
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  patients: [],
};

const patientSlice = createSlice({
  name: "patients",
  initialState,
  reducers: {
    // Adds a patient object to the list. Payload should be { id, name }.
    addPatient(state, action) {
      state.patients.push(action.payload);
    },

    // Removes a patient by id (payload is the id).
    deletePatient(state, action) {
      state.patients = state.patients.filter(
        (patient) => patient.id !== action.payload
      );
    },
  },
});

// actions and reducer are automatically generated by createSlice
export const { addPatient, deletePatient } = patientSlice.actions;
export default patientSlice.reducer;
